### ISSUE TITLE
Mindboggle crash: BrokenProcessPool

### ISSUE THREAD

**Issue by shnizzedy** [shnizzedy/nipype#1]
### Actual behavior

```Python
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/site-packages/traits/has_traits.py", line 1563, in __setstate__
    self.trait_set(trait_change_notify=trait_change_notify, **state)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/site-packages/traits/has_traits.py", line 1666, in trait_set
    setattr(self, name, value)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 317, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 141, in validate
    self.error(objekt, name, str(value))
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/site-packages/traits/trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'intensity_image' trait of a LabelGeometryInputSpec instance must be a pathlike object or string representing an existing file, but a value of '[]' <class 'str'> was specified.

exception calling callback for <Future at 0x7f0cc832ff98 state=finished raised BrokenProcessPool>

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 149, in _async_cllback
    result = args.result()
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

exception calling callback for <Future at 0x7f0cc82f0a90 state=finished raised BrokenProcessPool>

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 149, in _async_callback
    result = args.result()
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/miniconda-latest/envs/mb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

### Expected behavior

no crash

### Script/Workflow details

```BASH
singularity run \
-B /cbica/projects/RBC/RBC_RAWDATA/bidsdatasets/PNC/.git:/.git \
-B /cbica/projects/RBC/RBC_RAWDATA/bidsdatasets/PNC/sub-1417920839/ses-PNC1/anat:/home/jovyan/work \
-B /cbica/projects/RBC/RBC_RAWDATA/bidsdatasets/PNC/sub-1417920839/ses-PNC1/anat:/home/jovyan/work:ro \
-B /cbica/projects/RBC/CPACTesting/Pipeline_Timing/Mindboggle/Output/PNC/sub-1417920839_15_test:/MBoutput -e  \
/cbica/projects/RBC/CPACTesting/Pipeline_Timing/Mindboggle/mindboggle.img m\
mindboggle123 \
/home/jovyan/work/sub-1417920839_ses-PNC1_acq-refaced_T1w.nii.gz \
--out /MBoutput \
--working /MBoutput/working \
--id sub-1417920839 \
--plugin MultiProc --plugin_args "dict(n_procs=4,memory_gb=15)" --fs_openmp 4 --ants_num_threads 4 --mb_num_threads 4
```

**Comment by shnizzedy** [comment]
related: [<img src="https://neurostars.org/uploads/default/optimized/1X/eadd889a719a1e6370fbe086d518eafd6cd4586c_2_32x32.png" alt="NeuroStars" height="12px"> Fmriprep-docker: BrokenProcessPool](https://neurostars.org/t/fmriprep-docker-brokenprocesspool/17300)

**Comment by shnizzedy** [comment]
related: [<img src="https://neurostars.org/uploads/default/optimized/1X/eadd889a719a1e6370fbe086d518eafd6cd4586c_2_32x32.png" alt="NeuroStars" height="12px"> Memory allocation issues with fMRIPrep, Singularity and HPC](https://neurostars.org/t/memory-allocation-issues-with-fmriprep-singularity-and-hpc/2759/4)

**Comment by shnizzedy** [comment]
related: [<img src="https://neurostars.org/uploads/default/optimized/1X/eadd889a719a1e6370fbe086d518eafd6cd4586c_2_32x32.png" alt="NeuroStars" height="12px"> Memory Issue When Processing Large Amount of Data](https://neurostars.org/t/memory-issue-when-processing-large-amount-of-data/2562/5)
